# Generated by Django 4.2.7 on 2024-03-31 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',)},
        ),
    ]
